#!/usr/bin/env node
/*
 * Bundle the admin SPA: client/main.ts → public/dashboard/app.js.
 *
 * The client is authored as TypeScript ES modules under client/ and shipped as the one
 * framework-free, dependency-free, plain-JS asset the browser has always received. Only
 * the pipeline that produces app.js is new; what is served, how it is fingerprinted
 * (scripts/stamp-admin-assets.mjs), and how public/_headers caches it are unchanged.
 * app.js is generated and gitignored: the committed `?v=` stamp in index.html is a hash
 * of these bytes, so the build must be deterministic — no build-time defines, no
 * environment-dependent output — or the stamp would flip between dev and deploy.
 *
 * Modes:
 *   (default)  build once and exit non-zero on error.
 *   --watch    keep rebuilding as client/ changes (esbuild's incremental context, ~10ms a
 *              rebuild), re-stamping index.html after each successful build so the SPA's
 *              dev-mode poll (client/dev_reload.ts) sees the new hash. Errors are printed
 *              loudly and the previous bundle stays in place. The hand-authored
 *              styles.css is outside esbuild's build, so watch mode also re-stamps when
 *              it changes — that is what lets the poll hot-swap a CSS edit.
 *
 * Runs at every entry point that needs the bundle: `npm run dev` (scripts/dev.mjs, in
 * --watch mode), wrangler's build.command (so a bare `wrangler deploy` can never ship a
 * stale bundle), and pretest (so the stamp check hashes a fresh build).
 */
import { spawnSync } from "node:child_process";
import { watch } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/** @type {esbuild.BuildOptions} */
const options = {
  absWorkingDir: ROOT,
  entryPoints: ["client/main.ts"],
  outfile: "public/dashboard/app.js",
  bundle: true,
  format: "iife",
  target: "es2022",
  sourcemap: true,
  // Readable output on purpose: the served file is still something you can open and
  // read in the browser's devtools, and a stack trace stays meaningful with the map.
  minify: false,
  logLevel: "info",
  banner: {
    js: "// GENERATED by scripts/build-client.mjs from client/ — edit the source there, never this file.",
  },
};

// Re-fingerprint index.html against the new bytes. Best-effort in watch mode (a failure
// only leaves a stale `?v=`, which the next successful build re-stamps).
function stamp() {
  const r = spawnSync(process.execPath, [join(ROOT, "scripts", "stamp-admin-assets.mjs")], {
    stdio: "inherit",
  });
  if (r.status !== 0) {
    console.warn("[client] admin asset fingerprinting failed (continuing)");
  }
}

if (process.argv.includes("--watch")) {
  const ctx = await esbuild.context({
    ...options,
    plugins: [
      {
        name: "restamp-on-build",
        setup(build) {
          build.onEnd((result) => {
            if (result.errors.length === 0) {
              stamp();
            }
          });
        },
      },
    ],
  });
  await ctx.watch();

  // styles.css is served as authored, so only its stamp needs refreshing. Watch the
  // directory rather than the file: an editor that saves by rename replaces the inode,
  // which a single-file watch would silently lose. Debounced, since one save can land as
  // several events.
  let cssTimer = null;
  watch(join(ROOT, "public", "dashboard"), (_event, filename) => {
    // A null filename (some platforms) is treated as "maybe": the stamp is a no-op when current.
    if (filename && filename !== "styles.css") {
      return;
    }
    clearTimeout(cssTimer);
    cssTimer = setTimeout(stamp, 50);
  });

  console.log("[client] watching client/ and styles.css — rebuilding and re-stamping on change");
} else {
  await esbuild.build(options);
}
