/**
 * Environment bindings + resolved config.
 *
 * `Env` (from `worker-configuration.d.ts`, generated by `wrangler types`) holds
 * the D1/R2 bindings and the public `vars`. Secrets arrive as additional string
 * bindings; we declare them here as an optional `Secrets` interface so the code
 * type-checks whether or not a local `.dev.vars` was present when types were
 * generated. `AppEnv` is what handlers receive.
 */

export interface Secrets {
  /**
   * Symmetric secret for signing/verifying the local-dev admin token. Ships in
   * `.dev.vars.example` (so `cp .dev.vars.example .dev.vars` gives a working dev
   * secret) but is NOT committed to `wrangler.jsonc` — a deployed env has no value,
   * which keeps the dev auth path fail-closed. Only honored in a dev-shaped env
   * anyway (see `getConfig`); Cloudflare Access is the gate when deployed.
   */
  DEV_AUTH_SECRET?: string;
  /** Cloudflare Access team domain, e.g. `your-team.cloudflareaccess.com`. */
  ACCESS_TEAM_DOMAIN?: string;
  /** Cloudflare Access application AUD tag. */
  ACCESS_AUD?: string;
  /** Optional comma-separated allowlist of human admin emails (Access logins). */
  ACCESS_ALLOWED_EMAILS?: string;
  /** SES / SigV4. */
  AWS_ACCESS_KEY_ID?: string;
  AWS_SECRET_ACCESS_KEY?: string;
  SES_CONFIGURATION_SET?: string;
  SNS_TOPIC_ARN?: string;
  /** Resend. */
  RESEND_API_KEY?: string;
  RESEND_WEBHOOK_SECRET?: string;
  /**
   * Dev-only opt-in for the seeded send simulation (SPEC §10). When truthy in a
   * dev-shaped env, the fake transport is swapped for the pacing/edge-state simulation
   * so an in-flight send is watchable; unset (the default) keeps the plain, instant
   * fake. Ships commented in `.dev.vars.example`; never set in a deployed env.
   */
  SIMULATE_SENDS?: string;
}

/**
 * Optional public vars: not secrets, but left out of `wrangler.jsonc` by default, so
 * they are declared here rather than generated into `Env`.
 */
export interface OptionalVars {
  /**
   * Subrequests (D1 statements plus outbound requests) one invocation of the send path
   * may make. Unset means the Workers Free plan's 50; raise it on Workers Paid.
   */
  SUBREQUEST_BUDGET?: string;
}

export type AppEnv = Env & Secrets & OptionalVars;

export type ProviderName = "fake" | "ses" | "resend";

export interface Config {
  provider: ProviderName;
  /** Origin the app is served from (API + reader routes). */
  appOrigin: string;
  /** Origin the public archive lives on. Defaults to `appOrigin` (self-contained);
   *  set to the apex only as the opt-in Cloudflare enhancement (SPEC §11). */
  archiveOrigin: string;
  /** Base path for archive pages, e.g. `/archive`. Drives both the emitted
   *  archive URL and the route that serves it (SPEC §11); defaults to `/archive`. */
  archiveBasePath: string;
  /** Public base URL for R2-served images. Defaults to the Worker's own `/media`
   *  route; a `media.` custom domain is the optional upgrade (SPEC §11). */
  mediaPublicBase: string;
  /** Sending identity domain, e.g. `send.example.com`. */
  sendingDomain: string;
  /** `From:` header value. */
  fromAddress: string;
  /** AWS region for SES. */
  awsRegion: string;
  /** Cloudflare Access (optional; enables JWT validation when both are set). */
  accessTeamDomain?: string;
  accessAud?: string;
  /** Optional allowlist of human admin emails; empty/unset allows any valid Access login. */
  accessAllowedEmails?: string[];
  /**
   * True only in a dev-shaped env with the dev credential live (fake transport, no
   * Access, dev secret present) — the single case where `/dashboard` is reachable
   * without an Access wall, because the editor auto-mints a dev token on load. Gates
   * the dev-only "Open dashboard" link the public reader surface injects for a local
   * developer (SPEC §5, §11); structurally false in any deployed env, so the reader
   * surface never links toward the Access gate there. Presentation only — the route
   * gate in `app.ts` is identical in every environment.
   */
  devMode: boolean;
  /**
   * Local-dev admin-token secret, resolved ONLY in a dev-shaped env (fake transport,
   * no Access configured). Undefined in any deployed env, which disables the dev
   * credential path entirely — Access is then the only door.
   */
  devAuthSecret?: string;
  /**
   * Whether to run the dev-only seeded send simulation instead of the plain fake
   * transport (SPEC §10). True only in a dev-shaped env with `SIMULATE_SENDS` set —
   * structurally false once deployed (a real provider is configured there), so it can
   * never pace or fabricate events against a real inbox. Opt-in; the default is off.
   */
  simulateSends: boolean;
  /**
   * How many subrequests (D1 statements plus outbound requests) one invocation of the
   * send path may make: the send loop stops starting batches before it would pass this,
   * and the next sweep tick continues. Defaults to the Workers Free plan's 50, so a new
   * deployment is correct on any plan; Workers Paid allows 1,000 D1 queries.
   */
  subrequestBudget: number;
}

/** The Workers Free plan's per-invocation subrequest limit, the default budget. */
export const DEFAULT_SUBREQUEST_BUDGET = 50;
/** The least a sweep tick needs to find a send and deliver one batch of it. A lower
 *  `SUBREQUEST_BUDGET` would start nothing and stall every send silently, so it is
 *  raised to this. */
export const MIN_SUBREQUEST_BUDGET = 25;

const orUndefined = (v: string | undefined): string | undefined =>
  v && v.length > 0 ? v : undefined;

/** Leading-slash, no-trailing-slash form; defaults to `/archive`. Drives both
 *  the archive URL and the route registered to serve it, so the two can't drift. */
function normalizeBasePath(v: string | undefined): string {
  const raw = (orUndefined(v) ?? "/archive").trim();
  const withLead = raw.startsWith("/") ? raw : `/${raw}`;
  return withLead.length > 1 && withLead.endsWith("/") ? withLead.slice(0, -1) : withLead;
}

/** Resolve the typed `Config` from raw bindings. Pure; no I/O.
 *  Self-contained by default (SPEC §11): the archive origin and media base fall
 *  back to the app's own origin, so a deployment that sets only `APP_ORIGIN`
 *  serves archives and images on its own hostname with no further assumptions. */
export function getConfig(env: AppEnv): Config {
  const appOrigin = env.APP_ORIGIN;
  const provider = (env.PROVIDER as ProviderName) ?? "fake";
  const accessTeamDomain = orUndefined(env.ACCESS_TEAM_DOMAIN);
  // Belt-and-suspenders: only honor the dev credential when the env is unambiguously
  // dev-shaped — fake transport AND no Access configured. Combined with the secret
  // never being committed (it lives in the gitignored `.dev.vars`, not in
  // `wrangler.jsonc` vars), a deployed Worker has no secret and this stays undefined
  // — the dev auth path is off, Access is the only door. This one predicate is also
  // what `devMode` keys on, so "this is local dev" has a single source.
  const devShaped = provider === "fake" && !accessTeamDomain;
  const devAuthSecret = devShaped ? orUndefined(env.DEV_AUTH_SECRET) : undefined;
  return {
    provider,
    appOrigin,
    archiveOrigin: orUndefined(env.ARCHIVE_ORIGIN) ?? appOrigin,
    archiveBasePath: normalizeBasePath(env.ARCHIVE_BASE_PATH),
    mediaPublicBase: orUndefined(env.MEDIA_PUBLIC_BASE) ?? `${appOrigin}/media`,
    sendingDomain: env.SENDING_DOMAIN,
    fromAddress: env.FROM_ADDRESS,
    awsRegion: env.AWS_REGION,
    accessTeamDomain,
    accessAud: orUndefined(env.ACCESS_AUD),
    accessAllowedEmails: parseEmailList(env.ACCESS_ALLOWED_EMAILS),
    // Show the dev-only dashboard link exactly when clicking it would work: the
    // dev credential path is live (dev-shaped AND the secret resolved). Never true
    // in a deployed env, so the reader surface stays clean of any admin link there.
    devMode: devAuthSecret !== undefined,
    devAuthSecret,
    // Only ever active in a dev-shaped env; a deployed env runs a real provider, so the
    // simulation can never engage there whatever the var says.
    simulateSends: devShaped && isTruthy(env.SIMULATE_SENDS),
    subrequestBudget: Math.max(
      MIN_SUBREQUEST_BUDGET,
      parsePositiveInt(env.SUBREQUEST_BUDGET) ?? DEFAULT_SUBREQUEST_BUDGET,
    ),
  };
}

/** Treat the usual "on" spellings as truthy for a dev opt-in flag. */
function isTruthy(v: string | undefined): boolean {
  if (!v) {
    return false;
  }
  const s = v.trim().toLowerCase();
  return s === "1" || s === "true" || s === "yes" || s === "on";
}

/** A whole number above zero, or undefined for anything else (unset, blank, junk). */
function parsePositiveInt(v: string | undefined): number | undefined {
  const n = Number(v?.trim());
  return v && Number.isInteger(n) && n > 0 ? n : undefined;
}

function parseEmailList(v: string | undefined): string[] | undefined {
  if (!v) {
    return undefined;
  }
  const list = v
    .split(",")
    .map((e) => e.trim().toLowerCase())
    .filter(Boolean);
  return list.length ? list : undefined;
}
