/**
 * Environment bindings + resolved config.
 *
 * `Env` (from `worker-configuration.d.ts`, generated by `wrangler types`) holds
 * the D1/R2 bindings and the public `vars`. Secrets arrive as additional string
 * bindings; we declare them here as an optional `Secrets` interface so the code
 * type-checks whether or not a local `.dev.vars` was present when types were
 * generated. `AppEnv` is what handlers receive.
 *
 * `getConfig` takes nothing on trust: deploy config that would run but do the wrong thing
 * (an unknown provider, a missing origin, a real provider without its credentials or still
 * on the template's example.com placeholders, a minimum lead under the sweep's one-minute
 * tick or over a day) throws a `ConfigError` naming the variable.
 */

import {
  DEFAULT_MIN_LEAD_MS,
  formatLead,
  MIN_LEAD_CEILING_MS,
  MIN_LEAD_FLOOR_MS,
} from "../shared/sends";
import {
  SIMULATION_FAULTS,
  SIMULATION_PROFILES,
  type SimulationFaults,
  type SimulationProfile,
  type SimulationView,
} from "../shared/settings";
import {
  isProviderName,
  PROVIDER_NAMES,
  type ProviderName,
  REQUIRED_VARS,
} from "./providers/requirements";

export type { ProviderName };

export interface Secrets {
  /**
   * Symmetric secret for signing/verifying the local-dev admin token. Ships in
   * `.dev.vars.example` (so `cp .dev.vars.example .dev.vars` gives a working dev
   * secret) but is NOT committed to `wrangler.jsonc` — a deployed env has no value,
   * which keeps the dev auth path fail-closed. Only honored in a dev-shaped env
   * anyway (see `getConfig`); Cloudflare Access is the gate when deployed.
   */
  DEV_AUTH_SECRET?: string;
  /** Cloudflare Access team domain, e.g. `your-team.cloudflareaccess.com`. */
  ACCESS_TEAM_DOMAIN?: string;
  /** Cloudflare Access application AUD tag. */
  ACCESS_AUD?: string;
  /** Optional comma-separated allowlist of human admin emails (Access logins). */
  ACCESS_ALLOWED_EMAILS?: string;
  /** SES / SigV4. */
  AWS_ACCESS_KEY_ID?: string;
  AWS_SECRET_ACCESS_KEY?: string;
  SES_CONFIGURATION_SET?: string;
  /** The SES account's maximum send rate, in messages a second (optional). */
  SES_MAX_SEND_RATE?: string;
  SNS_TOPIC_ARN?: string;
  /** Resend. */
  RESEND_API_KEY?: string;
  RESEND_WEBHOOK_SECRET?: string;
  /**
   * The local send simulation (SPEC §10): which provider it models, `resend`, `ses`, or
   * `generic` (`1`), optionally with `:none` for no injected failures; `off` or unset for
   * the plain, instant fake. Honored only in a dev-shaped env, so never in a deployed one.
   * `.dev.vars.example` ships it on.
   */
  SIMULATE_SENDS?: string;
}

/**
 * Optional public vars: not secrets, but left out of `wrangler.jsonc` by default, so
 * they are declared here rather than generated into `Env`.
 */
export interface OptionalVars {
  /**
   * The origin the public archive's links use, when it is surfaced on a website apex
   * (SPEC §11). Unset means `APP_ORIGIN`.
   */
  ARCHIVE_ORIGIN?: string;
  /** Base URL images are served from, when a media custom domain is set. Unset means
   *  `${APP_ORIGIN}/media`. */
  MEDIA_PUBLIC_BASE?: string;
  /**
   * Subrequests (D1 statements plus outbound requests) one invocation of the send path
   * may make. Unset means the Workers Free plan's 50; raise it on Workers Paid.
   */
  SUBREQUEST_BUDGET?: string;
  /**
   * The minimum lead in seconds (SPEC §6): how long every send stays visible and cancelable
   * before it fires, at the least. Unset means five minutes; below sixty or above a day (86400) is refused.
   */
  MIN_LEAD_SECONDS?: string;
  /**
   * The `From:` of the notifications that email the publisher through Cloudflare (SPEC §8): an
   * address on a domain onboarded to Cloudflare's email sending. Unset means
   * `kestrel@` the app's own hostname.
   */
  NOTIFY_FROM?: string;
}

/**
 * Optional bindings, declared by hand because the development config never carries them,
 * so `wrangler types` does not generate them into `Env`.
 */
export interface OptionalBindings {
  /**
   * Cloudflare's `send_email` binding, the channel that tells the publisher when a send
   * goes out or runs into a problem (SPEC §8). Deploy-time infrastructure (SPEC §9): its presence
   * picks the channel, and it is never declared for development, where notifications go to the
   * in-memory fake.
   */
  NOTIFY?: SendEmail;
}

export type AppEnv = Env & Secrets & OptionalVars & OptionalBindings;

/**
 * How notifications reach the publisher (SPEC §8): Cloudflare's own email when the `NOTIFY`
 * binding is declared, the newsletter's provider otherwise, and the in-memory fake in a
 * dev-shaped env whatever is bound, so development can never reach a real inbox.
 */
export type NotifyChannel = "fake" | "cloudflare" | "provider";

export interface Config {
  provider: ProviderName;
  /** Origin the app is served from (API + reader routes). */
  appOrigin: string;
  /** Origin the public archive lives on. Defaults to `appOrigin` (self-contained);
   *  set to the apex only as the opt-in Cloudflare enhancement (SPEC §11). */
  archiveOrigin: string;
  /** Base path for archive pages, e.g. `/archive`. Drives both the emitted
   *  archive URL and the route that serves it (SPEC §11); defaults to `/archive`. */
  archiveBasePath: string;
  /** Public base URL for R2-served images. Defaults to the Worker's own `/media`
   *  route; a `media.` custom domain is the optional upgrade (SPEC §11). */
  mediaPublicBase: string;
  /** Sending identity domain, e.g. `send.example.com`. */
  sendingDomain: string;
  /** `From:` header value. */
  fromAddress: string;
  /** AWS region for SES. */
  awsRegion: string;
  /**
   * The SES account's maximum send rate, in messages a second, which the send loop paces
   * to: going over it is a throttle, which halts the send for at least a minute. Defaults
   * to 14, a new production account's rate; the SES sandbox allows 1.
   */
  sesMaxSendRate: number;
  /** Cloudflare Access (optional; enables JWT validation when both are set). */
  accessTeamDomain?: string;
  accessAud?: string;
  /** Optional allowlist of human admin emails; empty/unset allows any valid Access login. */
  accessAllowedEmails?: string[];
  /**
   * True only in a dev-shaped env with the dev credential live (fake transport, no
   * Access, a loopback `APP_ORIGIN`, dev secret present): the single case where
   * `/dashboard` is reachable without an Access wall, because the editor auto-mints a
   * dev token on load. It decides whether the `/api/dev/*` routes exist at all (`app.ts`
   * registers them only here), and gates the dev-only "Open dashboard" link the public
   * reader surface injects for a local developer (SPEC §5, §11). Structurally false in
   * any deployed env, so there the dev routes are absent and the reader surface never
   * links toward the Access gate. The admin/public gate in `app.ts` is identical in every
   * environment.
   */
  devMode: boolean;
  /**
   * Local-dev admin-token secret, resolved ONLY in a dev-shaped env (see `devMode`).
   * Undefined in any deployed env, which disables the dev credential path entirely:
   * Access is then the only door.
   */
  devAuthSecret?: string;
  /**
   * The local send simulation that stands in for a provider on list sends (SPEC §10), or
   * null for the plain fake. Only ever set in a dev-shaped env, from `SIMULATE_SENDS`, so
   * it is structurally null once deployed (a real provider is configured there) and can
   * never pace or fabricate events against a real inbox.
   */
  simulation: SimulationView | null;
  /**
   * How many subrequests (D1 statements plus outbound requests) one invocation of the
   * send path may make: the send loop stops starting batches before it would pass this,
   * and the next sweep tick continues. D1 statements are held to Cloudflare's own cap of
   * 1,000 besides (`budget.ts`). Defaults to the Workers Free plan's 50, so a new
   * deployment is correct on any plan; Workers Paid allows 10,000.
   */
  subrequestBudget: number;
  /**
   * The minimum lead (SPEC §6, I6): the least time between a request to send and the send
   * firing, which every schedule, send now, reschedule, and re-make enforces. Deploy config,
   * never a preference behind the API: the API is also Claude's door, and a review window
   * Claude could shorten through it would be no guard against Claude.
   */
  minLeadMs: number;
  /** The channel notifications to the publisher go through (see `NotifyChannel`). */
  notifyChannel: NotifyChannel;
  /** The `From:` a notification carries: `NOTIFY_FROM` on the Cloudflare channel, else the
   *  newsletter's own `From:`, the only sender its provider will take. */
  notifyFrom: string;
}

/** A new SES production account's maximum send rate, in messages a second. */
export const DEFAULT_SES_MAX_SEND_RATE = 14;
/** The Workers Free plan's per-invocation subrequest limit, the default budget. */
export const DEFAULT_SUBREQUEST_BUDGET = 50;
/** The least a sweep tick needs to find a send and deliver one batch of it, beside what it
 *  holds back for its own checks and one notification. A lower `SUBREQUEST_BUDGET` would
 *  start nothing and stall every send silently, so it is raised to this. */
export const MIN_SUBREQUEST_BUDGET = 30;

const orUndefined = (v: string | undefined): string | undefined =>
  v && v.length > 0 ? v : undefined;

/** Leading-slash, no-trailing-slash form; defaults to `/archive`. Drives both
 *  the archive URL and the route registered to serve it, so the two can't drift. */
function normalizeBasePath(v: string | undefined): string {
  const raw = (orUndefined(v) ?? "/archive").trim();
  const withLead = raw.startsWith("/") ? raw : `/${raw}`;
  return withLead.length > 1 && withLead.endsWith("/") ? withLead.slice(0, -1) : withLead;
}

/**
 * Deploy config the app cannot run on as given. Names the variable, so the 500 it becomes
 * and the line it logs both say what to fix. Never carries a secret's value: secrets are
 * only ever checked for presence.
 */
export class ConfigError extends Error {
  constructor(
    readonly variable: string,
    detail: string,
  ) {
    super(`${variable} ${detail}`);
    this.name = "ConfigError";
  }
}

/** Resolve the typed `Config` from raw bindings. Pure; no I/O. Throws `ConfigError` on
 *  deploy config that would run wrong rather than fail (see the module header).
 *  Self-contained by default (SPEC §11): the archive origin and media base fall
 *  back to the app's own origin, so a deployment that sets only `APP_ORIGIN`
 *  serves archives and images on its own hostname with no further assumptions. */
export function getConfig(env: AppEnv): Config {
  const provider = readProvider(env.PROVIDER);
  const appOrigin = readOrigin("APP_ORIGIN", env.APP_ORIGIN);
  if (!appOrigin) {
    throw new ConfigError("APP_ORIGIN", "is not set; it is the origin the app is served from");
  }
  const archiveOrigin = readOrigin("ARCHIVE_ORIGIN", env.ARCHIVE_ORIGIN) ?? appOrigin;
  const mediaPublicBase =
    readBaseUrl("MEDIA_PUBLIC_BASE", env.MEDIA_PUBLIC_BASE) ?? `${appOrigin}/media`;
  if (provider !== "fake") {
    requireRealProviderConfig(provider, env, { appOrigin, archiveOrigin, mediaPublicBase });
  }
  const accessTeamDomain = orUndefined(env.ACCESS_TEAM_DOMAIN);
  // Belt-and-suspenders: only honor the dev credential when the env is unambiguously
  // dev-shaped: fake transport, no Access configured, AND an origin on this machine.
  // Combined with the secret never being committed (it lives in the gitignored
  // `.dev.vars`, not in `wrangler.jsonc` vars), a deployed Worker has no secret and this
  // stays undefined, so the dev auth path is off and Access is the only door. The loopback
  // origin also catches a fake, Access-less deploy given its real hostname with `.dev.vars`
  // uploaded as secrets. Config alone cannot tell the development config deployed wholly
  // unchanged (its origin still names localhost) from local dev; that deploy is
  // misconfigured anyway, since every link it emits points at localhost. A real provider
  // or Access, either of which every real deployment has, turns this path off regardless.
  // This one predicate is also what `devMode` (and so the dev routes) keys on, so "this is
  // local dev" has a single source.
  const devShaped = provider === "fake" && !accessTeamDomain && isLoopbackOrigin(appOrigin);
  const devAuthSecret = devShaped ? orUndefined(env.DEV_AUTH_SECRET) : undefined;
  const notifyChannel: NotifyChannel = devShaped ? "fake" : env.NOTIFY ? "cloudflare" : "provider";
  return {
    provider,
    appOrigin,
    archiveOrigin,
    archiveBasePath: normalizeBasePath(env.ARCHIVE_BASE_PATH),
    mediaPublicBase,
    sendingDomain: env.SENDING_DOMAIN,
    fromAddress: env.FROM_ADDRESS,
    awsRegion: env.AWS_REGION,
    sesMaxSendRate:
      readPositiveInt("SES_MAX_SEND_RATE", env.SES_MAX_SEND_RATE) ?? DEFAULT_SES_MAX_SEND_RATE,
    accessTeamDomain,
    accessAud: orUndefined(env.ACCESS_AUD),
    accessAllowedEmails: parseEmailList(env.ACCESS_ALLOWED_EMAILS),
    // Show the dev-only dashboard link, and register the dev routes, exactly when the
    // dev credential path is live (dev-shaped AND the secret resolved). Never true in a
    // deployed env, so the reader surface stays clean of any admin link there.
    devMode: devAuthSecret !== undefined,
    devAuthSecret,
    // Only ever read in a dev-shaped env; a deployed env runs a real provider, so the
    // simulation can never engage there whatever the var says.
    simulation: devShaped ? readSimulation(env.SIMULATE_SENDS) : null,
    subrequestBudget: Math.max(
      MIN_SUBREQUEST_BUDGET,
      readPositiveInt("SUBREQUEST_BUDGET", env.SUBREQUEST_BUDGET) ?? DEFAULT_SUBREQUEST_BUDGET,
    ),
    minLeadMs: readMinLead(env.MIN_LEAD_SECONDS),
    notifyChannel,
    notifyFrom:
      notifyChannel === "cloudflare"
        ? (orUndefined(env.NOTIFY_FROM) ?? `Kestrel <kestrel@${new URL(appOrigin).hostname}>`)
        : env.FROM_ADDRESS,
  };
}

/** `PROVIDER` as one of the known names, exactly as spelled. Unset means the fake (the
 *  development config); anything else unknown is an error, never a quiet fake that would
 *  record every recipient accepted and mail no one. */
function readProvider(v: string | undefined): ProviderName {
  const raw = orUndefined(v);
  if (raw === undefined) {
    return "fake";
  }
  if (!isProviderName(raw)) {
    throw new ConfigError("PROVIDER", `must be one of ${PROVIDER_NAMES.join(", ")}, not "${raw}"`);
  }
  return raw;
}

/**
 * What a real transport needs before it may run: its credentials, a `From:`, and no
 * example.com placeholder left from the template, whose links and images would otherwise
 * go out in every email and, as archive URLs are permanent (I3), stay wrong forever.
 */
function requireRealProviderConfig(
  provider: Exclude<ProviderName, "fake">,
  env: AppEnv,
  origins: { appOrigin: string; archiveOrigin: string; mediaPublicBase: string },
): void {
  for (const name of [...REQUIRED_VARS[provider], "FROM_ADDRESS"] as const) {
    const value = env[name];
    if (typeof value !== "string" || value.trim() === "") {
      throw new ConfigError(name, `is not set; PROVIDER "${provider}" needs it`);
    }
  }
  const hosts: [string, string][] = [
    ["APP_ORIGIN", new URL(origins.appOrigin).hostname],
    ["ARCHIVE_ORIGIN", new URL(origins.archiveOrigin).hostname],
    ["MEDIA_PUBLIC_BASE", new URL(origins.mediaPublicBase).hostname],
    ["FROM_ADDRESS", emailDomain("FROM_ADDRESS", env.FROM_ADDRESS)],
  ];
  if (orUndefined(env.SENDING_DOMAIN)) {
    hosts.push(["SENDING_DOMAIN", env.SENDING_DOMAIN.trim()]);
  }
  for (const [name, host] of hosts) {
    if (isPlaceholderHost(host)) {
      throw new ConfigError(
        name,
        `is still on the template's example.com placeholder; PROVIDER "${provider}" sends real email`,
      );
    }
  }
}

/** The domain of a `From:` value, `Name <local@domain>` or a bare address. */
function emailDomain(name: string, from: string): string {
  // The address is the last `<…>`, so a display name that itself contains angle brackets
  // is not mistaken for it.
  const address = /<([^<>]*)>\s*$/.exec(from)?.[1] ?? from;
  const at = address.lastIndexOf("@");
  if (at < 1 || at === address.length - 1) {
    throw new ConfigError(name, `must be an email address, optionally with a name, not "${from}"`);
  }
  return address.slice(at + 1).trim();
}

function isPlaceholderHost(host: string): boolean {
  const h = host.toLowerCase().replace(/\.$/, "");
  return h === "example.com" || h.endsWith(".example.com");
}

function isLoopbackOrigin(origin: string): boolean {
  const host = new URL(origin).hostname;
  return host === "localhost" || host === "127.0.0.1";
}

/** A URL value as it may appear in an error, which is a public 500 and a log line: any
 *  `user:password@` it carries is hidden, so a credential never leaves in a message. */
function redactUserinfo(raw: string): string {
  return raw.replace(/\/\/[^/?#]*@/, "//…@");
}

/** An http(s) URL with no credentials, query, or fragment. */
function parseHttpUrl(name: string, raw: string): URL {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    throw new ConfigError(name, `must be an http(s) URL, not "${redactUserinfo(raw)}"`);
  }
  if (
    (url.protocol !== "http:" && url.protocol !== "https:") ||
    url.username ||
    url.password ||
    url.search ||
    url.hash
  ) {
    throw new ConfigError(name, `must be a plain http(s) URL, not "${redactUserinfo(raw)}"`);
  }
  return url;
}

/** An origin var (scheme, host, port; a trailing slash is dropped), or undefined when
 *  unset. A path is refused rather than ignored, since it would never be honored. */
function readOrigin(name: string, v: string | undefined): string | undefined {
  const raw = orUndefined(v?.trim());
  if (raw === undefined) {
    return undefined;
  }
  const url = parseHttpUrl(name, raw);
  if (!/^\/*$/.test(url.pathname)) {
    throw new ConfigError(
      name,
      `must be an origin (scheme and host, no path), not "${redactUserinfo(raw)}"`,
    );
  }
  return url.origin;
}

/** A base URL var (an origin, optionally with a path) with trailing slashes dropped, so
 *  the URLs built on it never double a slash; undefined when unset. */
function readBaseUrl(name: string, v: string | undefined): string | undefined {
  const raw = orUndefined(v?.trim());
  if (raw === undefined) {
    return undefined;
  }
  const url = parseHttpUrl(name, raw);
  return `${url.origin}${url.pathname.replace(/\/+$/, "")}`;
}

/** A whole number above zero, or undefined when unset or blank. Anything else is refused
 *  rather than quietly defaulted, so a typo can't pass for the default. */
function readPositiveInt(name: string, v: string | undefined): number | undefined {
  const raw = orUndefined(v?.trim());
  if (raw === undefined) {
    return undefined;
  }
  const n = Number(raw);
  if (!Number.isInteger(n) || n <= 0) {
    throw new ConfigError(name, `must be a whole number above zero, not "${raw}"`);
  }
  return n;
}

/**
 * `MIN_LEAD_SECONDS` in milliseconds, or the default when unset. One floor in every
 * environment, local dev included: the sweep runs once a minute, so under that the tick,
 * not the lead, would decide when a send fires. The ceiling, one day, catches a value in
 * milliseconds. A value outside the two is refused rather than clamped, so a deployment
 * never runs on a lead other than the one it names.
 */
function readMinLead(v: string | undefined): number {
  const seconds = readPositiveInt("MIN_LEAD_SECONDS", v);
  if (seconds === undefined) {
    return DEFAULT_MIN_LEAD_MS;
  }
  if (seconds * 1000 < MIN_LEAD_FLOOR_MS) {
    throw new ConfigError(
      "MIN_LEAD_SECONDS",
      `must be at least ${MIN_LEAD_FLOOR_MS / 1000}, not "${v?.trim()}": the send sweep runs once a minute, so under ${formatLead(MIN_LEAD_FLOOR_MS)} the tick, not the lead, would decide when a send fires`,
    );
  }
  if (seconds * 1000 > MIN_LEAD_CEILING_MS) {
    throw new ConfigError(
      "MIN_LEAD_SECONDS",
      `must be at most ${MIN_LEAD_CEILING_MS / 1000} (one day), not "${v?.trim()}": it is in seconds, and it is the least wait before every send, not a limit on how far out one can be scheduled`,
    );
  }
  return seconds * 1000;
}

/** The spellings that turn the simulation off, and those that pick the generic profile. */
const SIMULATION_OFF = new Set(["", "0", "off", "false", "no"]);
const SIMULATION_GENERIC = new Set(["1", "on", "true", "yes"]);

/**
 * `SIMULATE_SENDS` as a profile and fault level, or null for the plain fake: `off` (or
 * unset), a profile (`generic`, or `1`, `resend`, `ses`), and optionally `:realistic` (the
 * default) or `:none`. Anything else is refused rather than read as off, so a typo can't
 * quietly turn the simulation off or pick the wrong provider.
 */
function readSimulation(v: string | undefined): SimulationView | null {
  const raw = (v ?? "").trim().toLowerCase();
  if (SIMULATION_OFF.has(raw)) {
    return null;
  }
  const [name = "", faults = "realistic", ...rest] = raw.split(":");
  const profile = SIMULATION_GENERIC.has(name) ? "generic" : name;
  if (
    rest.length > 0 ||
    !(SIMULATION_PROFILES as readonly string[]).includes(profile) ||
    !(SIMULATION_FAULTS as readonly string[]).includes(faults)
  ) {
    throw new ConfigError(
      "SIMULATE_SENDS",
      `must be off, or one of ${SIMULATION_PROFILES.join(", ")} (or 1), optionally followed by :${SIMULATION_FAULTS.join(" or :")}, not "${v?.trim()}"`,
    );
  }
  return { profile: profile as SimulationProfile, faults: faults as SimulationFaults };
}

function parseEmailList(v: string | undefined): string[] | undefined {
  if (!v) {
    return undefined;
  }
  const list = v
    .split(",")
    .map((e) => e.trim().toLowerCase())
    .filter(Boolean);
  return list.length ? list : undefined;
}
