/**
 * Environment bindings + resolved config.
 *
 * `Env` (from `worker-configuration.d.ts`, generated by `wrangler types`) holds
 * the D1/R2 bindings and the public `vars`. Secrets arrive as additional string
 * bindings; we declare them here as an optional `Secrets` interface so the code
 * type-checks whether or not a local `.dev.vars` was present when types were
 * generated. `AppEnv` is what handlers receive.
 */

export interface Secrets {
  /**
   * Symmetric secret for signing/verifying the local-dev admin token. Ships in
   * `.dev.vars.example` (so `cp .dev.vars.example .dev.vars` gives a working dev
   * secret) but is NOT committed to `wrangler.jsonc` — a deployed env has no value,
   * which keeps the dev auth path fail-closed. Only honored in a dev-shaped env
   * anyway (see `getConfig`); Cloudflare Access is the gate when deployed.
   */
  DEV_AUTH_SECRET?: string;
  /** Cloudflare Access team domain, e.g. `your-team.cloudflareaccess.com`. */
  ACCESS_TEAM_DOMAIN?: string;
  /** Cloudflare Access application AUD tag. */
  ACCESS_AUD?: string;
  /** Optional comma-separated allowlist of human admin emails (Access logins). */
  ACCESS_ALLOWED_EMAILS?: string;
  /** SES / SigV4. */
  AWS_ACCESS_KEY_ID?: string;
  AWS_SECRET_ACCESS_KEY?: string;
  SES_CONFIGURATION_SET?: string;
  SNS_TOPIC_ARN?: string;
  /** Resend. */
  RESEND_API_KEY?: string;
  RESEND_WEBHOOK_SECRET?: string;
}

export type AppEnv = Env & Secrets;

export type ProviderName = "fake" | "ses" | "resend";

export interface Config {
  provider: ProviderName;
  /** Origin the app is served from (API + reader routes). */
  appOrigin: string;
  /** Origin the public archive lives on. Defaults to `appOrigin` (self-contained);
   *  set to the apex only as the opt-in Cloudflare enhancement (SPEC §10). */
  archiveOrigin: string;
  /** Base path for archive pages, e.g. `/archive`. Drives both the emitted
   *  archive URL and the route that serves it (SPEC §10); defaults to `/archive`. */
  archiveBasePath: string;
  /** Public base URL for R2-served images. Defaults to the Worker's own `/media`
   *  route; a `media.` custom domain is the optional upgrade (SPEC §10). */
  mediaPublicBase: string;
  /** Sending identity domain, e.g. `send.example.com`. */
  sendingDomain: string;
  /** `From:` header value. */
  fromAddress: string;
  /** AWS region for SES. */
  awsRegion: string;
  /** Cloudflare Access (optional; enables JWT validation when both are set). */
  accessTeamDomain?: string;
  accessAud?: string;
  /** Optional allowlist of human admin emails; empty/unset allows any valid Access login. */
  accessAllowedEmails?: string[];
  /**
   * True only in a dev-shaped env with the dev credential live (fake transport, no
   * Access, dev secret present) — the single case where `/dashboard` is reachable
   * without an Access wall, because the editor auto-mints a dev token on load. Gates
   * the dev-only "Open dashboard" link the public reader surface injects for a local
   * developer (SPEC §5, §10); structurally false in any deployed env, so the reader
   * surface never links toward the Access gate there. Presentation only — the route
   * gate in `app.ts` is identical in every environment.
   */
  devMode: boolean;
  /**
   * Local-dev admin-token secret, resolved ONLY in a dev-shaped env (fake transport,
   * no Access configured). Undefined in any deployed env, which disables the dev
   * credential path entirely — Access is then the only door.
   */
  devAuthSecret?: string;
}

const orUndefined = (v: string | undefined): string | undefined =>
  v && v.length > 0 ? v : undefined;

/** Leading-slash, no-trailing-slash form; defaults to `/archive`. Drives both
 *  the archive URL and the route registered to serve it, so the two can't drift. */
function normalizeBasePath(v: string | undefined): string {
  const raw = (orUndefined(v) ?? "/archive").trim();
  const withLead = raw.startsWith("/") ? raw : `/${raw}`;
  return withLead.length > 1 && withLead.endsWith("/") ? withLead.slice(0, -1) : withLead;
}

/** Resolve the typed `Config` from raw bindings. Pure; no I/O.
 *  Self-contained by default (SPEC §10): the archive origin and media base fall
 *  back to the app's own origin, so a deployment that sets only `APP_ORIGIN`
 *  serves archives and images on its own hostname with no further assumptions. */
export function getConfig(env: AppEnv): Config {
  const appOrigin = env.APP_ORIGIN;
  const provider = (env.PROVIDER as ProviderName) ?? "fake";
  const accessTeamDomain = orUndefined(env.ACCESS_TEAM_DOMAIN);
  // Belt-and-suspenders: only honor the dev credential when the env is unambiguously
  // dev-shaped — fake transport AND no Access configured. Combined with the secret
  // never being committed (it lives in the gitignored `.dev.vars`, not in
  // `wrangler.jsonc` vars), a deployed Worker has no secret and this stays undefined
  // — the dev auth path is off, Access is the only door. This one predicate is also
  // what `devMode` keys on, so "this is local dev" has a single source.
  const devShaped = provider === "fake" && !accessTeamDomain;
  const devAuthSecret = devShaped ? orUndefined(env.DEV_AUTH_SECRET) : undefined;
  return {
    provider,
    appOrigin,
    archiveOrigin: orUndefined(env.ARCHIVE_ORIGIN) ?? appOrigin,
    archiveBasePath: normalizeBasePath(env.ARCHIVE_BASE_PATH),
    mediaPublicBase: orUndefined(env.MEDIA_PUBLIC_BASE) ?? `${appOrigin}/media`,
    sendingDomain: env.SENDING_DOMAIN,
    fromAddress: env.FROM_ADDRESS,
    awsRegion: env.AWS_REGION,
    accessTeamDomain,
    accessAud: orUndefined(env.ACCESS_AUD),
    accessAllowedEmails: parseEmailList(env.ACCESS_ALLOWED_EMAILS),
    // Show the dev-only dashboard link exactly when clicking it would work: the
    // dev credential path is live (dev-shaped AND the secret resolved). Never true
    // in a deployed env, so the reader surface stays clean of any admin link there.
    devMode: devAuthSecret !== undefined,
    devAuthSecret,
  };
}

function parseEmailList(v: string | undefined): string[] | undefined {
  if (!v) {
    return undefined;
  }
  const list = v
    .split(",")
    .map((e) => e.trim().toLowerCase())
    .filter(Boolean);
  return list.length ? list : undefined;
}
